polarity = "dark"
[font]
name = "Inter Regular"
package = "inter"
[cursor]
name = "Nordzy-cursors"
package = "nordzy-cursors-theme"
size = 24
[icons]
name = "Papirus-Dark"
package = "papirus-nord.override {accent = \"auroramagenta\";}"
[colors]
base00 = "2E3440"
base01 = "3B4252"
base02 = "434C5E"
base03 = "4c566a"
base04 = "D8DEE9"
base05 = "E5E9F0"
base06 = "ECEFF4"
base07 = "8FBCBB"
base08 = "BF616A"
base09 = "D08770"
base0A = "EBCB8B"
base0B = "A3BE8C"
base0C = "88C0D0"
base0D = "B48EAD"
base0E = "5E81AC"
base0F = "81A1C1"
